//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.vijayganduri.nighttimedisplay;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.vijayganduri.nighttimedisplay.R.id;

public final class DisplayActivity_
    extends DisplayActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        timeTextView = ((TextView) findViewById(id.time_text));
        menuOptions = ((LinearLayout) findViewById(id.menuOptions));
        timeBackgroundTextView = ((TextView) findViewById(id.time_text_background));
        {
            View view = findViewById(id.displayBackground);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DisplayActivity_.this.backGroundClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.settings_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DisplayActivity_.this.settingsClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.about_button);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DisplayActivity_.this.aboutClicked();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static DisplayActivity_.IntentBuilder_ intent(Context context) {
        return new DisplayActivity_.IntentBuilder_(context);
    }

    @Override
    public void updateTime(final String time) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DisplayActivity_.super.updateTime(time);
                } catch (RuntimeException e) {
                    Log.e("DisplayActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void calculateTime() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    DisplayActivity_.super.calculateTime();
                } catch (RuntimeException e) {
                    Log.e("DisplayActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DisplayActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DisplayActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
